---
repos:
- id: /.*/
  allowed_overrides: [apply_requirements, workflow]
workflows:
  terragrunt:
    plan:
      steps:
      - run: terragrunt plan --terragrunt-non-interactive --terragrunt-parallelism 1 -no-color -out=$PLANFILE
    apply:
      steps:
      - run: terragrunt apply --terragrunt-non-interactive --terragrunt-parallelism 1 -no-color $PLANFILE
